version: '3.8'

services:
  pdpj-auth:
    build: .
    container_name: pdpj-auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PJE_URL=https://pje.cloud.tjpe.jus.br
      - PORTAL_URL=https://portaldeservicos.pdpj.jus.br
      - MAX_SESSIONS=5
      - SESSION_EXPIRATION=3600000
      - HEADLESS=true
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - API_SECRET=${API_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - pdpj-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/webhook/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pdpj-network:
    driver: bridge
