[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "cups", "libdrm", "gtk3", "libxcomposite", "libxdamage", "libxfixes", "libxrandr", "gbm", "alsa-lib", "pango", "cairo"]

[phases.install]
cmds = [
  "npm install",
  "mkdir -p /usr/bin",
  "ln -sf $(which chromium) /usr/bin/chromium"
]

[start]
cmd = "npm start"
